theme:
    name: material
    palette:
        scheme: slate
    features:
        - toc.integrate
extra_css:
    - css/labs.css
markdown_extensions:
    - admonition
    - pymdownx.highlight:
      anchor_linenums: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences
nav:
    - index.md
extra:
    generator: false
plugins:
    - mkdocs-jupyter